### ISSUE TITLE
recipes

### ISSUE THREAD

**Issue by hetec** [socobo/SocoboPlusPlus#11]
The recipe component of socobo

functions:

Backend:

- [x] Add a new Recipe #18 
- [x] Update a Recipe
- [x] Delete a Recipe
- [x] Get all Recipes
- [x] Get all Recipes by SocoboUserId

Frontend:

- [x] #62 Add recipe Module

feature ideas:
- [x] Tags like meat, fish, vegetarian and so on
- [x] Steps (add, edit, show ...)
- [x] Ingredients section
- [x] Meta Information (Cooking time, Skill level ...)
- [x] Recipe Collections / Groups (Christmas, Fitness, Fastfood)
- [x] Rating system (public and private?)
- [x] Hearting system

**Comment by hetec** [comment]
The recipe component of socobo

**Comment by flashback2k14** [comment]
- [ ] Add a new Recipe #18

**Comment by flashback2k14** [comment]
@hetec what did you think?

**Comment by hetec** [comment]
Looks good so far
