### ISSUE TITLE
change to MongoDB

### ISSUE THREAD

**Issue by flashback2k14** [socobo/SocoboPlusPlus#80]
- database schema  [Link](https://drive.google.com/file/d/0B_-yrSSE644XX1cxT0hPR3BqUnc/view?usp=sharing) [Diagram](https://www.draw.io/?state=%7B%22ids%22:%5B%220B_-yrSSE644XX1cxT0hPR3BqUnc%22%5D,%22action%22:%22open%22,%22userId%22:%22103183073414466549375%22%7D#G0B_-yrSSE644XX1cxT0hPR3BqUnc)
- mongoDB Relationship [Link](https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/)
- mongoDB Tutorial [Link](https://www.tutorialspoint.com/mongodb/index.htm)
- useful library
  - https://github.com/szokodiakos/typegoose
  - http://codingsans.com/blog/mongoose-models-using-typescript-classes

DEV Branch: **80-change-to-MongoDB** create from Branch **75-extend-database-functionality**
- ToDo's:
  - [x] database setup #84 
  - [x] socobouser collection + repository #85 
  - [x] recipe collection + repository #87 
  - [x] fooditem collection + repository #90

**Comment by flashback2k14** [comment]
@hetec i have translated our postgres database schema into a mongoDB schema. Please take a look. i'm not sure if all is right. thanks.

**Comment by hetec** [comment]
@flashback2k14 Some ideas to the new schema. I would maybe embed the recipeSteps, recipeMetaData and the recipe Images directly into the recipe document?! Because each recipe always has its unique steps and images we will not duplicate data if we include them into the recipes. On the other hand we don't need to do separate db queries to fetch the data. To have a own collection for the categories is ok since different recipes can use the same categories.

The fooditem stuff looks very fine for me!

**Comment by flashback2k14** [comment]
@hetec i follow the provided mongoDB pattern for [Model One-to-Many Relationships with Document References](https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/)

> To avoid mutable, growing arrays, store the publisher reference inside the book document:

maybe i have misunderstood it. Could you please check the link!?

**Comment by hetec** [comment]
The recipe ingredients and recipe user stuff looks also fine

**Comment by flashback2k14** [comment]
okay the _maybe parts_ could integrated into the schema?

**Comment by hetec** [comment]
Yes I think they are 👍

**Comment by flashback2k14** [comment]
okay it's integrated! :-)

**Comment by hetec** [comment]
I understand the point of referencing ids but I think we will not have growing arrays for the steps, images and meta data because we always only have a very limited amount of them per recipe.

https://docs.mongodb.com/manual/tutorial/model-embedded-one-to-many-relationships-between-documents/#data-modeling-example-one-to-many

Additionally these data are always unique, so there will never be two recipes which could use a identical id für example a step or so. So I don't really see the point to put them in a separate collection.

For the categories this is different, since there exist multiple recipes which can reuse categories via referencing a id. So here the referencing way is the better on I think

**Comment by flashback2k14** [comment]
okay. could you please update the schema into tab MongoDB v1.1?

**Comment by hetec** [comment]
Yes I will do this. If I'm wrong and we need the reference approach later, I think will can always switch back again.

**Comment by hetec** [comment]
Done! Maybe you could check it out

**Comment by flashback2k14** [comment]
recipeMetaData is an object not a collection!?

**Comment by flashback2k14** [comment]
@hetec looks complete now.
